#tomcat启动端口
server:
  port: 1000

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/small?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatisplus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #表前缀
    table-prefix: sf_
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wdx.flyleg.pojo


  thymeleaf: #关闭缓存
    cache: false

#qq资源
oauth:
  qq:
    #appid
    client_id: 101698287  #qq\u5E94\u7528\u7A0B\u5E8F APP ID
    #appkey
    client_secret: 3264980ccc09236770181afcf37be62f  #qq\u5E94\u7528\u7A0B\u5E8F APP Key
    #回调路径
    redirect_uri: http://localhost:1000/authorize/qq

    code_callback_uri: https://graph.qq.com/oauth2.0/authorize

    access_token_callback_uri: https://graph.qq.com/oauth2.0/token

    openid_callback_uri: https://graph.qq.com/oauth2.0/me

    user_info_callback_uri: https://graph.qq.com/user/get_user_info

#cas
cas :
  server-url : http://localhost:8080/cas

  service : http://localhost:1000
    #\u767B\u5F55\u6210\u529F\u5730\u5740
#    loginSuccessUrl : index
    #\u6743\u9650\u8BA4\u8BC1\u5931\u8D25\u8DF3\u8F6C\u5730\u5740
#    unauthorizedUrl : error.html



