#tomcat\u542F\u52A8\u7AEF\u53E3
server:
  port: 1000

#\u6570\u636E\u5E93
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csq?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
    id-type: 0
    #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
    field-strategy: 1
    #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
    db-column-underline: true
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    refresh-mapper: true
    #\u8868\u524D\u7F00
    table-prefix: sf_
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wdx.flyleg.pojo


  thymeleaf: #\u5173\u95EDthymeleaf\u7F13\u5B58
    cache: false

#\u81EA\u5B9A\u4E49qq\u8D44\u6E90
oauth:
  qq:
    #\u4F60\u7684appid
    client_id: 101698287  #qq\u5E94\u7528\u7A0B\u5E8F APP ID
    #\u4F60\u7684appkey
    client_secret: 3264980ccc09236770181afcf37be62f  #qq\u5E94\u7528\u7A0B\u5E8F APP Key
    #\u4F60\u63A5\u6536\u54CD\u5E94code\u7801\u5730\u5740  (\u56DE\u8C03\u5730\u5740)
    redirect_uri: http://localhost:1000/authorize/qq
    #\u817E\u8BAF\u83B7\u53D6code\u7801\u5730\u5740
    code_callback_uri: https://graph.qq.com/oauth2.0/authorize
    #\u817E\u8BAF\u83B7\u53D6access_token\u5730\u5740
    access_token_callback_uri: https://graph.qq.com/oauth2.0/token
    #\u817E\u8BAF\u83B7\u53D6openid\u5730\u5740
    openid_callback_uri: https://graph.qq.com/oauth2.0/me
    #\u817E\u8BAF\u83B7\u53D6\u7528\u6237\u4FE1\u606F\u5730\u5740
    user_info_callback_uri: https://graph.qq.com/user/get_user_info

